default:
    trainer: ppo

    batch_size: 1024
    buffer_size: 10240
    learning_rate: 3.0e-4
    learning_rate_schedule: linear

    beta: 5.0e-3    
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 3

    vis_encode_type: simple
    normalize: false 
    hidden_units: 128
    num_layers: 2
    sequence_length: 64
    memory_size: 256
    
    max_steps: 5.0e5 
    time_horizon: 64
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true
    init_path: null

    use_recurrent: false
    
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

        # curiosity module
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
            learning_rate: 3.0e-4

ParkrCar:
    trainer: ppo
    model_path: ./models/ParkrCar
    summary_path: ./summaries/ParkrCar